server:
  port: 5000

spring:
  profiles:
    active: local
  jpa:
    show-sql: true
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    locations: "filesystem:db-schema/sql/"
    schemas: ${spring.datasource.hikari.schema}
  datasource:
    hikari:
      schema: "public"

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG


distance-threshold: 5000
